name: api_default_project
description: A new Flutter project.


publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  http: ^1.1.0
  keyboard_dismisser: ^3.0.0
  zoom_tap_animation: ^1.1.0
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.7.3
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.1
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
