name: api_default_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  dio: ^5.3.2
  http: ^1.1.0
  sqflite: ^2.3.0
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  zoom_tap_animation: ^1.1.0
  cached_network_image: ^3.2.3
  lottie: ^2.5.0
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.0.1
  flutter_bloc: ^8.1.3
  mask_text_input_formatter: ^2.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
