name: api_default_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  http: ^1.1.0
  zoom_tap_animation: ^1.1.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  permission_handler: ^10.4.3
  on_audio_query: ^2.9.0
  flutter_bloc: ^8.1.3
  audioplayers: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/translations/
     - assets/fonts/
     - assets/music/
     - assets/svg/
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
